/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package hacker.rank.ebury;

import java.util.Arrays;
import java.util.HashSet;
import java.util.List;
import java.util.Set;

// Count the duplicated elements in an array

public class CountDuplicates {
    public static int countDuplicate(List<Integer> numbers) {
        int duplicates = 0;

        // Create a set to lookup the numbers O(1)
        Set<Integer> set = new HashSet<>();

        // Check which ones we already counted O(1)
        Set<Integer> checked = new HashSet<>();

        // For each number O(n)
        for (int number : numbers) {
            // If it is in the set, it's a duplicate, otherwise, add it
            if (set.contains(number) && !checked.contains(number)) {
                duplicates++;
                checked.add(number);
            } else {
                set.add(number);    // We would not need to put in the else
            }
        }

        return duplicates;
    }

    public static void main(String[] args) {
        System.out.println(countDuplicate(Arrays.asList(1, 3, 3, 4, 4, 4))); // 2
        System.out.println(countDuplicate(Arrays.asList(1, 3, 3, 4, 4, 3, 5, 8, 5))); // 3
    }
}
