/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package hacker.rank.ebury;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.HashSet;
import java.util.List;
import java.util.Set;
import java.util.SortedSet;
import java.util.TreeSet;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

// Find domains in html-style strings

public class DetectDomainNames {

    public static String getPotentialDomains(List<String> lines) {
        // Ok, I did not read the exercise completely, using the URL parser will not work, coming back
        // the regular expression, playing here https://regexr.com/

        final Pattern pattern = Pattern.compile("(http|https)://(www.|ww2.|web.)?([a-zA-Z0-9-]+(\\.[a-zA-Z0-9-]+)+)");
        /*
        (http|https) -- protocols
        :// -- literal
        (www.|ww2.)? -- optional web site indicators
        ([a-zA-Z0-9-]+(\.[a-zA-Z0-9-]+)+) -- subdomains + domains
         */

        // Use a set to keep the ordering
        SortedSet<String> domains = new TreeSet<>();

        // For each line
        for (String line : lines) {
            // For each match in the line, extract the host
            Matcher matcher = pattern.matcher(line);
            while (matcher.find()) {
                domains.add(matcher.group(3));
            }
        }
        return String.join(";", new ArrayList<>(domains));
    }

    public static void main(String[] args) {
        System.out.println(getPotentialDomains(Arrays.asList(
                "http://play.google.com/store/apps/details?id=com.skgames.trafficracer%22"
                ,"http://mplay.google.co.in/sadfask/asdkfals?dk=10"
                ,"http://lplay.google.co.in/sadfask/asdkfals?dk=10"
                ,"http://play.google.co.in/sadfask/asdkfals?dk=10"
                ,"http://tplay.google.co.in/sadfask/asdkfals?dk=10"
                ,"http://www.google.co.in/sadfask/asdkfals?dk=10"
                ,"asdjkhadskjhdsakjhdsa http://web.archive.org adkljdaslkdasjdaklj"
                ,"www.google.co.in/sadfask/asdkfals?dk=10"
                ,"guasoirjaskjhlad https://www.gustavo.co.in/sadfask/asdkfals?dk=10 dioahdaoiasdhadsioh"
                ,"http://user:pass@google.com/?a=b#asdd"
                ,"https://www.compzets.com?asd=10"
                ,"www.compzets.com?asd=10"
        )));
        // archive.org;compzets.com;google.co.in;gustavo.co.in;lplay.google.co.in;mplay.google.co.in;play.google.co.in;play.google.com;tplay.google.co.in
    }
}
