/*
 * This Spock specification was generated by the Gradle 'init' task.
 */
package hacker.rank.ebury

import spock.lang.Specification

class CountDuplicatesTest extends Specification {
    def "someLibraryMethod returns true"() {
        setup:
        def lib = new CountDuplicates()

        when:
        def result = lib.someLibraryMethod()

        then:
        result == true
    }
}
